# Generated by Django 4.0.3 on 2022-04-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comments_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',)},
        ),
    ]
